### ISSUE TITLE
Absence of exact buy/sell signals for individual stocks.

### ISSUE THREAD

**Issue by jayshinde10** [devfinwiz/Fin-Maestro#13]
A new module should be present to identify exact buy and sell points for a specific stock. 
Possibly for both intraday data as well as in the form of positional call.

**Comment by devfinwiz** [comment]
Sounds good. You are basically expecting a visual (a plot) that would have something like long/short (green/red arrows) markers on it? Right?

**Comment by jayshinde10** [comment]
Yes, correct

**Comment by devfinwiz** [comment]
Cool, you can view it here. We are working on having a similar provision for intraday data frame as well. 
https://github.com/devfinwiz/Fin-Maestro/tree/master/SignalsGenerator
