### ISSUE TITLE
Issue with requirements.txt due to marge request

### ISSUE THREAD

**Issue by 0xMimir** [devfinwiz/Fin-Maestro#26]
In `requirements.txt` there are two entries for requests, one `requests==2.28.2` made by DEV_FINWIZ and one made by @devfinwiz 5 hours ago, same goes for `gradio`

**Comment by devfinwiz** [comment]
Feel free to contribute with any new features or bug fixes if you find any. Thanks for your contribution towards Fin-Maestro.
