### ISSUE TITLE
Regarding 1st pre-requisite

### ISSUE THREAD

**Issue by asafravid** [devfinwiz/Fin-Maestro#39]
Hi, I do not understand how to install https://vitejs.dev/guide/
What are the required steps?

**Comment by devfinwiz** [comment]
@xmagcx

**Comment by xmagcx** [comment]
hi @asafravid, I provide a slightly more detailed guide about the installation steps, anyway the link I shared is the official one for the Vitejs framework, I understand that it might not be so simple to carry out.  https://positiwise.com/blog/how-to-install-vite-js-on-your-computer

**Comment by devfinwiz** [comment]
Closing the issue assuming the concern has been answered. 
Kindly re-open if needed.
